---
title: "Potential Outcomes"
output: html_notebook
---

An attempt at explaining the potential outcomes in words, code, data, and plots.

## Setting up our population

```{r}
# install.packages("tidyverse")
# install.packages("randomNames")
library(tidyverse)

population_size <- 1e6
sample_sizes <- 10 ^ seq(1, log(population_size, 10))
num_simulations <- 100
base_income <- 1e4
base_income_sd <- 1e3

effect_size = 2 * base_income_sd
effect_sd = base_income_sd

ethnicities <- c("Indian", "Asian", "Black", "Hispanic", "White", "Arabic")
genders <- c("Female", "Male")

population <- randomNames::randomNames(population_size, return.complete.data = TRUE) %>%
  mutate(gender = map_chr(gender, ~ genders[.x + 1]),
         ethnicity = map_chr(ethnicity, ~ ethnicities[.x])) %>%
  mutate(across(where(is.character), as.factor)) %>%
  mutate(income = round(rnorm(population_size, base_income, base_income_sd))) %>%
  mutate(potential_0 = income) %>%
  mutate(potential_1 = round(potential_0 +
           rnorm(population_size, effect_size, effect_sd))) %>%
  mutate(id = row_number())

summary(population)

population %>%
  ggplot(aes(ethnicity, fill = ethnicity)) +
  geom_bar()

population %>%
  ggplot(aes(gender, fill = gender)) +
  geom_bar()

population %>%
  ggplot(aes(income)) +
  geom_density()

population %>%
  pivot_longer(c(potential_0, potential_1)) %>%
  ggplot(aes(value, fill = name)) +
  geom_density(alpha = 0.2)
```

## Varying sample size

### Full compliance

```{r}
lapply(sample_sizes, function(sample_size) {
  population %>%
    sample_n(sample_size) %>%
    select(first_name, starts_with("potential_")) %>%
    mutate(true_tx_effect = potential_1 - potential_0) %>%
    arrange(runif(n())) %>%
    mutate(group = if_else(row_number() < n() / 2, "treatment", "control")) %>%
    arrange(runif(n())) %>%
    mutate(observed_0 = if_else(group == "control", potential_0,
                                        NA_real_),
           observed_1 = if_else(group == "treatment", potential_1,
                                        NA_real_)) %>%
    bind_rows(summarise(., across(-c(group, first_name), mean, na.rm = TRUE)) %>%
                mutate(across(where(is.numeric), round, digits = 1),
                       first_name = "<<SUMMARY>>")) %>%
    mutate(observed_tx_effect = observed_1 - observed_0) %>%
    arrange(desc(row_number()))
})
```

### Non-compliance 

```{r}
#  (3/5 complier, 1/5 nevertaker, 1/5 alwaystaker)
complier_types <- c("alwaystaker", "alwaystaker",
                    "nevertaker", "nevertaker",
                    "complier", "complier", "complier",
                    "complier", "complier", "complier")
lapply(sample_sizes, function(sample_size) {
  population %>%
    # select sample_size units randomly
    sample_n(sample_size) %>%
    # select client name and potential outcomes
    select(id, first_name, starts_with("potential_")) %>%
    # calculate true unit-level treatment effect
    mutate(true_tx_effect = potential_1 - potential_0) %>%
    # randomly assign treatment and control (50/50)
    arrange(runif(n())) %>%
    mutate(group = if_else(row_number() < n() / 2, "treatment", "control")) %>%
    arrange(runif(n())) %>%
    # randomly assign complier types
    # mutate(compliance_group = complier_types[ntile(runif(n()), n = 5)]) %>%
    mutate(compliance_group = complier_types[floor(10 * runif(n())) + 1]) %>%
    # set observed outcomes based on control and treatment assignment
    mutate(observed_0 = if_else(group == "control", potential_0,
                                        NA_real_),
           observed_1 = if_else(group == "treatment", potential_1,
                                        NA_real_)) %>%
    # set observed outcomes based on complier type
    mutate(
      observed_0 = if_else(
        compliance_group == "alwaystaker" & !is.na(observed_0), potential_1,
        observed_0),
      observed_1 = if_else(
        compliance_group == "nevertaker" & !is.na(observed_1), potential_0,
        observed_1)) %>%
    # complier type shares
    mutate(is_taker_tx = if_else(
             group == "treatment",
             compliance_group %in% c("alwaystaker", "complier"), NA),
           is_taker_ctl = if_else(
             group == "control",
             compliance_group %in% c("alwaystaker"), NA)) %>%
    # calculate summaries
    bind_rows(
      summarise(., across(starts_with(c("observed_", "is_")), mean, na.rm = TRUE)) %>%
        mutate(across(where(is.numeric), round, digits = 1), first_name = "<<SUMMARY>>")
    ) %>%
    mutate(observed_itt_effect = observed_1 - observed_0) %>%
    arrange(desc(row_number())) %>%
    mutate(alpha = is_taker_tx - is_taker_ctl,
           cace = observed_itt_effect / alpha)
})
```